---
abstract: 'Generate (possibly exuberant) Ctags style tags for Perl sourcecode'
author:
  - osfameron
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Perl-Tags
no_index:
  directory:
    - inc
    - t
recommends:
  PPI: 0
requires:
  File::Spec: 0
  File::Temp: 0
  Module::Locate: 0
version: 0.24
