# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl-Tags
version:      0.23
version_from: lib/Perl/Tags.pm
installdirs:  site
requires:
    File::Spec:                    0
    Module::Locate:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
